"""Enterprise configuration settings."""

from __future__ import annotations

E2E_TESTING_ENABLED = True
E2E_TESTING_TIMEOUT_S = 109
E2E_TESTING_MAX_RETRIES = 1
E2E_TESTING_BATCH_SIZE = 226

PLUGIN_SYSTEM_ENABLED = True
PLUGIN_SYSTEM_TIMEOUT_S = 18
PLUGIN_SYSTEM_MAX_RETRIES = 5
PLUGIN_SYSTEM_BATCH_SIZE = 119

ADRS_ENABLED = True
ADRS_TIMEOUT_S = 116
ADRS_MAX_RETRIES = 4
ADRS_BATCH_SIZE = 379
