"""Enterprise configuration settings."""

from __future__ import annotations

E2E_TESTING_ENABLED = True
E2E_TESTING_TIMEOUT_S = 109
E2E_TESTING_MAX_RETRIES = 1
E2E_TESTING_BATCH_SIZE = 226

PLUGIN_SYSTEM_ENABLED = True
PLUGIN_SYSTEM_TIMEOUT_S = 18
PLUGIN_SYSTEM_MAX_RETRIES = 5
PLUGIN_SYSTEM_BATCH_SIZE = 119

ADRS_ENABLED = True
ADRS_TIMEOUT_S = 116
ADRS_MAX_RETRIES = 4
ADRS_BATCH_SIZE = 379

AUDIO_TRANSCODE_ENABLED = True
AUDIO_TRANSCODE_TIMEOUT_S = 7
AUDIO_TRANSCODE_MAX_RETRIES = 2
AUDIO_TRANSCODE_BATCH_SIZE = 414

USER_PREFERENCES_ENABLED = True
USER_PREFERENCES_TIMEOUT_S = 44
USER_PREFERENCES_MAX_RETRIES = 1
USER_PREFERENCES_BATCH_SIZE = 300

REAL_TIME_ENABLED = True
REAL_TIME_TIMEOUT_S = 65
REAL_TIME_MAX_RETRIES = 3
REAL_TIME_BATCH_SIZE = 185

EVENT_BUS_ENABLED = True
EVENT_BUS_TIMEOUT_S = 31
EVENT_BUS_MAX_RETRIES = 4
EVENT_BUS_BATCH_SIZE = 270

ENCRYPTION_ENABLED = True
ENCRYPTION_TIMEOUT_S = 73
ENCRYPTION_MAX_RETRIES = 3
ENCRYPTION_BATCH_SIZE = 257

API_KEYS_ENABLED = True
API_KEYS_TIMEOUT_S = 47
API_KEYS_MAX_RETRIES = 4
API_KEYS_BATCH_SIZE = 182

BILLING_ENABLED = True
BILLING_TIMEOUT_S = 84
BILLING_MAX_RETRIES = 3
BILLING_BATCH_SIZE = 50

MODEL_REGISTRY_ENABLED = True
MODEL_REGISTRY_TIMEOUT_S = 24
MODEL_REGISTRY_MAX_RETRIES = 4
MODEL_REGISTRY_BATCH_SIZE = 338

SSE_ENABLED = True
SSE_TIMEOUT_S = 66
SSE_MAX_RETRIES = 3
SSE_BATCH_SIZE = 260

INTEGRATION_TESTING_ENABLED = True
INTEGRATION_TESTING_TIMEOUT_S = 69
INTEGRATION_TESTING_MAX_RETRIES = 2
INTEGRATION_TESTING_BATCH_SIZE = 454
