"""Application constants for Mach."""

APP_NAME = "Mach"
APP_VERSION = "0.5.0"
MAX_AUDIO_DURATION_S = 600
MAX_UPLOAD_SIZE_MB = 100
SUPPORTED_FORMATS = {".wav", ".mp3", ".flac", ".ogg", ".m4a", ".aac"}
DEFAULT_SAMPLE_RATE = 22050
DEFAULT_HOP_LENGTH = 512
DEFAULT_N_MELS = 128
DEFAULT_N_FFT = 2048
DEFAULT_FADE_IN_S = 0.01
DEFAULT_FADE_OUT_S = 0.05
SUPPORTED_EXPORT_FORMATS = {"json", "csv", "tsv", "html", "md"}
MAX_COLLAB_PARTICIPANTS = 50
MAX_ANNOTATIONS_PER_ROOM = 500
DEFAULT_SHARE_EXPIRY_HOURS = 168
MAX_EFFECTS_CHAIN_LENGTH = 20
