"""HTML report generation with embedded charts."""
from __future__ import annotations
from bird_mach.reporting.pdf_report import AnalysisReport

class HTMLReportRenderer:
    """Render AnalysisReport as a styled HTML page."""
    def render(self, report: AnalysisReport) -> str:
        sections = ""
        for s in report._sections:
            sections += f"<section><h2>{s.title}</h2><p>{s.content}</p></section>\n"
        return f"""<!DOCTYPE html>
<html><head><title>{report.title}</title>
<style>body{{font-family:system-ui;background:#0f172a;color:#e2e8f0;max-width:800px;margin:0 auto;padding:2rem}}
h1{{color:#38bdf8}}h2{{color:#818cf8;border-bottom:1px solid #334155;padding-bottom:0.5rem}}
section{{margin:1.5rem 0}}</style></head>
<body><h1>{report.title}</h1>
<p><em>Generated by {report.author}</em></p>
{sections}</body></html>"""
