"""Generate analysis reports (text-based, PDF-ready structure)."""
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime

@dataclass
class ReportSection:
    title: str
    content: str
    chart_data: dict | None = None

class AnalysisReport:
    def __init__(self, title: str, author: str = "Mach"):
        self.title = title
        self.author = author
        self.created_at = datetime.now()
        self._sections: list[ReportSection] = []

    def add_section(self, title: str, content: str, chart_data: dict | None = None):
        self._sections.append(ReportSection(title, content, chart_data))

    def to_markdown(self) -> str:
        lines = [f"# {self.title}", f"*Generated by {self.author} on {self.created_at:%Y-%m-%d %H:%M}*", ""]
        for section in self._sections:
            lines.append(f"## {section.title}")
            lines.append(section.content)
            lines.append("")
        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "author": self.author,
            "created_at": self.created_at.isoformat(),
            "sections": [{"title": s.title, "content": s.content} for s in self._sections],
        }

    @property
    def section_count(self) -> int:
        return len(self._sections)
